export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const PLACEMENT_LIST_REQUEST = 'PLACEMENT_LIST_REQUEST';
export const PLACEMENT_LIST_SUCCESS = 'PLACEMENT_LIST_SUCCESS';
export const PLACEMENT_LIST_FAIL = 'PLACEMENT_LIST_FAIL';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const FETCH_USER_SENT_REQUESTS = 'FETCH_USER_SENT_REQUESTS';
export const SET_USER_SENT_REQUESTS = 'SET_USER_SENT_REQUESTS';
